# 1. Dá um nome fixo para o banco (senão o Spring cria um nome aleatório a cada restart)
spring.datasource.url=jdbc:h2:mem:pharmadber
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Mostra o SQL no console (O comando CREATE TABLE vai aparecer aqui)
spring.jpa.show-sql=true

# 3. Habilita o painel visual para acessarmos pelo navegador
spring.h2.console.enabled=true